name: Hprofile Actions
on: workflow_dispatch
jobs: 
  Testing: 
    runs-on: ubuntu-latest
    steps:
     - name: Code checkout
       uses: actions/checkout@v4
     - name: maven test
       run: mvn test
     - name: checkstyle
       run: mvn checkstyle:checkstyle#
     - name: set java 11
       uses: actions/setup-java@v3
       with:
         distribution: 'temurin'
         java-version: '11'

     - name: setup Sonarscanner
       uses: warchant/setup-sonar-scanner@v7

     - name: SonarQube Scan
       run: sonar-scanner
         -Dsonar.host.url=${{ secrets.SONAR_URL }}
         -Dsonar.login=${{ secrets.SONAR_TOKEN }}
         -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
         -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
         -Dsonar.sources=src/
         -Dsonar.junit.reportPaths=target/surefire-reports/
         -Dsonar.jaccoco.reportPaths=target/jacoco.exec
         -Dsonar.java.checkstyle.reportPaths=target/site/checkstyle-result.xml
         -Dsonar.java.binaries=target/classes/com/visualpathit/account
